# Here are some geometric properties of the robot stored
# wildcard so any node can read this
/**:
  ros__parameters:
    'd': 0.18
    'L_segment': 0.12
    'L_total': 0.24
    'yaw_offset_top': 60 # in degrees
    'wheel_radius': 0.2