// this is matlab code for creating a rotational matrix.
// Todo: Bring this somehow into Python/ROS.

function R = S_fun_1(t,in2,L1,m1,in5,in6,in7,in8)
%S_fun_1
%    R = S_fun_1(T,IN2,L1,M1,IN5,IN6,IN7,IN8)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    24-Dec-2025 16:46:36

Dx1 = in2(1,:);
Dy1 = in2(2,:);
t2 = Dx1.^2;
t3 = Dy1.^2;
t4 = t2+t3+1.0e-10;
t5 = 1.0./t4;
t6 = sqrt(t4);
t7 = 1.0./t6;
t8 = cos(t6);
t9 = sin(t6);
t10 = t8-1.0;
t11 = Dx1.*t7.*t9;
t12 = Dy1.*t7.*t9;
t13 = Dx1.*Dy1.*t5.*t10;
R = reshape([t2.*t5.*t10+1.0,t13,t11,t13,t3.*t5.*t10+1.0,t12,-t11,-t12,t8],[3,3]);
end